# Site settings
title: "Carlos Baia: Data Science, Machine Learning e Deep Learning"
author: "Carlos Baia"
email: carloshenriquebaia@gmail.com
description: "Artigos sobre Data Science, Machine Learning e Deep Learning. Desde os conceitos básicos até a implementação dos algoritmos com um dataset real usando Python."
baseurl: ""
url: "http://carlosbaia.com/"
title_description: "<b style='font-size:100%'>Engenheiro de Computação</b> e <b style='font-size:100%'>Desenvolvedor de Software</b> há mais de 10 anos, trabalho com segurança de informação e desenvolvo em C++ e Python em praticamente todo esse período. <b style='font-size:100%'>Scrum Master</b> e <b style='font-size:100%'>Gerente de Projetos</b> pela FGV.<br><br>Trabalho desenvolvendo tecnologias antifraudes que rodam em mais de 50 milhões de computadores. Nos últimos anos tenho atuado como <b style='font-size:100%'>Cientista de Dados</b> e aplicado <b style='font-size:100%'>Machine Learning</b> e <b style='font-size:100%'>Deep Learning</b> nos mais variados projetos."

title_image: "https://s.gravatar.com/avatar/a094eb0d6a2614158242087840f2a7d7?s=150"
google_analytics: "UA-71213574-1"
#disqus_account: carlosbaia
fb_app_id: "1035391459869025"
#github_repository: ""
addthis_id: ra-59cd7cc448900003
post_limit: 8

# Social usernames/URLs
email_link: mailto:carloshenriquebaia@gmail
skype_link: skype:carlos.henrique.baia
linkedin_link: https://br.linkedin.com/in/carloshenriquebaia
github_username: carlosbaia
#stackoverflow_link: 
#twitter_username:
#facebook_link: https://www.facebook.com/carloshenriquebaia
#google_plus_link: https://plus.google.com/+CarlosHenriqueBaia
kaggle_link: https://www.kaggle.com/carloshenriquebaia
medium_link: https://medium.com/@carlosbaia

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
