# Site settings
title: "Carlos Henrique Baia"
email: carloshenriquebaia@gmail.com
description: "Carlos Henrique Baia`s personal page"
baseurl: "Engenheiro de computação, desenvolvedor há mais de 10 anos, trabalho com segurança de informação em praticamente todo esse período, pelo menos 10 anos de experiência em C++ e mais de 5 anos em Python. Tenho experiência com metodologias ágeis e MBA em gerenciamento de projetos pela FGV.<br>Atualmente trabalho na GAS Tecnologia e desenvolvo tecnologias que rodam em mais de 40 milhões de computadores. Meu trabalho é todo focado na criação e evolução de tecnologias antifraudes. Mais recentemente tenho trabalhado como cientista de dados e usado apredizado de máquina no combate à fraude."
url: "http://carlosbaia.com/"
title_description: 

title_image: "https://s.gravatar.com/avatar/a094eb0d6a2614158242087840f2a7d7?s=200"
google_analytics: "UA-71213574-1"
#github_repository: ""
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
#twitter_username:
github_username: carlosbaia
linkedin_link: https://br.linkedin.com/in/carloshenriquebaia
facebook_link: https://www.facebook.com/carloshenriquebaia
email_link: mailto:carloshenriquebaia@gmail
#google_plus_link: https://plus.google.com/+CarlosHenriqueBaia
#stackoverflow_link: 

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
