# Site settings
title: "Carlos Henrique Baia"
email: carloshenriquebaia@gmail.com
description: "Carlos Henrique Baia`s personal page"
baseurl: ""
url: "http://carlosbaia.com/"
title_description: "Engenheiro de Computação e Desenvolvedor de Software há mais de 10 anos, trabalho com segurança de informação e desenvolvo em C++ e Python em praticamente todo esse período. Tenho experiência com metodologias ágeis e MBA em Gerenciamento de Projetos pela FGV.<br><br>Trabalho na GAS Tecnologia e desenvolvo tecnologias antifraudes que rodam em mais de 50 milhões de computadores. Recentemente tenho trabalhado como cientista de dados e usado aprendizado de máquina no combate à fraude."

title_image: "https://s.gravatar.com/avatar/a094eb0d6a2614158242087840f2a7d7?s=200"
google_analytics: "UA-71213574-1"
disqus_account: carloshenriquebaia
#github_repository: ""
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
email_link: mailto:carloshenriquebaia@gmail
skype_link: skype:carlos.henrique.baia
linkedin_link: https://br.linkedin.com/in/carloshenriquebaia
github_username: carlosbaia
#stackoverflow_link: 
#twitter_username:
facebook_link: https://www.facebook.com/carloshenriquebaia
#google_plus_link: https://plus.google.com/+CarlosHenriqueBaia

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
